---
# Playbook to install Ansible
- name: Add Ansible PPA repository
  apt_repository:
    repo: ppa:ansible/ansible

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: latest    